In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
!pwd

/Users/Muthu/Development/OptionList4/ml_notebooks

In [3]:
data = pd.read_csv("../ml_cp18//ml_cp18.csv")
data.describe()

,bid_size,ask_size,last_size,volume,bid_ask_delta,c_w1_n3_bid_ask_delta,c_w1_n3_ask,c_w1_n3_ask_size,c_w1_n3_bid,c_w1_n3_bid_size,...,c_w3_p3_bid_ask_delta,c_w3_p3_ask,c_w3_p3_ask_size,c_w3_p3_bid,c_w3_p3_bid_size,c_w3_p3_last,c_w3_p3_last_size,c_w3_p3_strike_delta,c_w3_p3_time_value,c_w3_p3_theta
count,23242.000000,23242.000000,23242.000000,2.324200e+04,23242.000000,23221.000000,23221.000000,23221.000000,23221.000000,23221.000000,...,22174.000000,22174.000000,22174.000000,22174.000000,22174.000000,22174.000000,22174.000000,22174.000000,22174.000000,22174.000000
mean,11.419069,12.619482,2.640134,5.780484e+05,-0.014356,-0.143011,6.097166,494.951079,5.954156,485.349813,...,-0.015615,1.734052,309.164472,1.718437,310.170109,1.725193,5.124876,-6.562156,8.288400,3.382115
std,10.074586,11.660392,4.716379,2.641619e+05,0.006119,0.059762,0.749796,433.432503,0.744555,418.485218,...,0.006295,0.223913,218.122760,0.223012,221.916924,0.224407,9.604160,0.738582,0.560458,0.273981
min,1.000000,1.000000,1.000000,2.010500e+04,-0.170000,-2.400000,-1.000000,0.000000,-1.000000,0.000000,...,-0.210000,-1.000000,0.000000,-1.000000,0.000000,1.270000,1.000000,-7.490000,4.660000,1.991453
25%,4.000000,5.000000,1.000000,3.556430e+05,-0.020000,-0.150000,5.450000,141.000000,5.300000,166.000000,...,-0.020000,1.600000,137.000000,1.580000,126.000000,1.590000,1.000000,-7.180000,7.890000,3.181410
50%,9.000000,11.000000,1.000000,6.253780e+05,-0.010000,-0.150000,5.950000,377.000000,5.800000,392.000000,...,-0.020000,1.680000,283.000000,1.660000,273.000000,1.670000,1.000000,-6.750000,8.410000,3.380475
75%,16.000000,18.000000,2.000000,8.034665e+05,-0.010000,-0.150000,6.650000,754.000000,6.500000,699.000000,...,-0.010000,1.810000,465.000000,1.790000,472.000000,1.807500,5.000000,-6.080000,8.760000,3.639713
max,375.000000,443.000000,144.000000,1.026599e+06,0.000000,0.000000,8.900000,3351.000000,7.550000,3211.000000,...,0.000000,2.400000,3242.000000,2.380000,1161.000000,2.400000,175.000000,-5.000000,9.125000,3.848915

In [4]:
data.head(3)

,bid_size,ask_size,last_size,volume,bid_ask_delta,c_w1_n3_bid_ask_delta,c_w1_n3_ask,c_w1_n3_ask_size,c_w1_n3_bid,c_w1_n3_bid_size,...,c_w3_p3_ask_size,c_w3_p3_bid,c_w3_p3_bid_size,c_w3_p3_last,c_w3_p3_last_size,c_w3_p3_strike_delta,c_w3_p3_time_value,c_w3_p3_theta,p60s_bucket_category,p300s_bucket_category
0,2.0,4.0,1.0,20105.0,-0.06,-0.70,7.05,1.0,6.35,101.0,...,9.0,1.52,9.0,1.66,4.0,-6.01,7.555,2.935120,NaN,NaN
1,2.0,6.0,1.0,20193.0,-0.04,-1.05,7.10,3.0,6.05,1.0,...,30.0,1.54,44.0,1.66,4.0,-5.98,7.545,2.931235,NaN,NaN
2,6.0,1.0,2.0,20196.0,-0.02,-1.30,7.35,1.0,6.05,1.0,...,13.0,1.56,21.0,1.57,1.0,-5.94,7.520,2.921523,NaN,NaN

In [5]:
data = data.dropna()
data.isnull().sum()
data = data.head(1000)

In [6]:
cols = data.columns.values.tolist()
len(cols)

187

In [7]:
X = data.drop(['p60s_bucket_category', 'p300s_bucket_category'], axis=1)
Y = data[['p300s_bucket_category']]

In [8]:
X

,bid_size,ask_size,last_size,volume,bid_ask_delta,c_w1_n3_bid_ask_delta,c_w1_n3_ask,c_w1_n3_ask_size,c_w1_n3_bid,c_w1_n3_bid_size,...,c_w3_p3_bid_ask_delta,c_w3_p3_ask,c_w3_p3_ask_size,c_w3_p3_bid,c_w3_p3_bid_size,c_w3_p3_last,c_w3_p3_last_size,c_w3_p3_strike_delta,c_w3_p3_time_value,c_w3_p3_theta
1217,6.0,409.0,10.0,114750.0,-0.01,-0.15,6.50,593.0,6.35,5.0,...,-0.01,1.56,299.0,1.55,91.0,1.56,1.0,-6.16,7.715,3.010614
1218,8.0,27.0,1.0,114752.0,-0.01,-0.15,6.35,158.0,6.20,152.0,...,-0.01,1.53,273.0,1.52,82.0,1.55,17.0,-6.29,7.815,3.049637
1219,13.0,19.0,1.0,114754.0,-0.02,-0.15,6.35,452.0,6.20,232.0,...,-0.01,1.53,490.0,1.52,10.0,1.52,10.0,-6.31,7.835,3.057442
1220,5.0,1.0,2.0,114757.0,-0.01,-0.15,6.35,445.0,6.20,21.0,...,-0.02,1.53,260.0,1.51,113.0,1.51,5.0,-6.33,7.850,3.063295
1221,2.0,25.0,10.0,114772.0,-0.02,-0.20,6.40,250.0,6.20,705.0,...,-0.02,1.54,449.0,1.52,423.0,1.51,5.0,-6.28,7.810,3.047686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2241,6.0,18.0,3.0,177165.0,-0.01,-0.15,5.65,443.0,5.50,805.0,...,-0.01,1.41,325.0,1.40,367.0,1.40,3.0,-7.03,8.435,3.304733
2242,5.0,20.0,3.0,177169.0,-0.01,-0.15,5.65,120.0,5.50,1041.0,...,-0.01,1.41,316.0,1.40,173.0,1.40,3.0,-7.03,8.435,3.304733
2243,2.0,15.0,3.0,177173.0,-0.01,-0.15,5.65,381.0,5.50,176.0,...,-0.01,1.40,55.0,1.39,648.0,1.40,3.0,-7.05,8.445,3.308651
2244,3.0,12.0,1.0,177176.0,-0.01,-0.15,5.60,1.0,5.45,771.0,...,-0.02,1.40,390.0,1.38,712.0,1.39,11.0,-7.08,8.470,3.318445
2245,35.0,5.0,10.0,177187.0,-0.02,-0.15,5.60,290.0,5.45,1307.0,...,-0.01,1.40,529.0,1.39,250.0,1.39,63.0,-7.09,8.485,3.324322

In [9]:
Y

     p300s_bucket_category
1217              q_6_1.18
1218              q_5_0.36
1219              q_5_0.36
1220              q_5_0.36
1221              q_5_0.36
...                    ...
2241             q_0_-0.42
2242             q_0_-0.42
2243             q_0_-0.42
2244             q_0_-0.42
2245             q_0_-0.42

[1000 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
X15_train, X15_test, y15_train, y15_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [16]:
from datetime import datetime
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from xgboost.sklearn import XGBClassifier

start_time = datetime.now()
# Various hyper-parameters to tune
xgb15 = XGBClassifier(objective='binary:logistic')
parameters = {'nthread':[4], #when use hyperthread, xgboost may become slower
              # 'objective':['reg:linear'],
              'learning_rate': [.03, 0.05, .07], #so called `eta` value
              'max_depth': [5, 6, 7],
              'min_child_weight': [4],
              'silent': [1],
              'subsample': [0.7],
              'colsample_bytree': [0.7],
              'n_estimators': [500]}

xgb15_grid = GridSearchCV(xgb15,
                        parameters,
                        cv = 2,
                        n_jobs = 5,
                        verbose=True)
xgb15_grid.fit(X15_train, y15_train)

stop_time = datetime.now()

Fitting 2 folds for each of 9 candidates, totalling 18 fits

/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Muthu/Development/OptionList4/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[15:18:47] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[15:18:47] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [18]:
print('15: best_score ', xgb15_grid.best_score_, ' params: ', xgb15_grid.best_params_)

15: best_score  0.66625  params:  {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'n_estimators': 500, 'nthread': 4, 'silent': 1, 'subsample': 0.7}

In [25]:
print('Start Timestamp : ', start_time.strftime("%d-%b-%Y (%H:%M:%S.%f)"))
print('Stop Timestamp : ', stop_time.strftime("%d-%b-%Y (%H:%M:%S.%f)"))
import math
td = stop_time - start_time
td_mins = int(math.floor((td).total_seconds() / 60))
td_secs = td.total_seconds() - int(math.floor((td).total_seconds() / 60)*60)
print(f'The difference is approx. {td_mins}:{td_secs:02.0f} minutes')

Start Timestamp :  19-Dec-2021 (15:18:05.171912)
Stop Timestamp :  19-Dec-2021 (15:18:53.031708)
The difference is approx. 0:47.859796 minutes