In [2]:
import pandas as pd

ids = [11, 22, 33, 44, 55, 66, 77]
countries = ['Spain', 'France', 'Spain', 'Germany', 'France']

df = pd.DataFrame(list(zip(ids, countries)),
                  columns=['Ids', 'Countries'])
df

   Ids Countries
0   11     Spain
1   22    France
2   33     Spain
3   44   Germany
4   55    France

In [4]:
y = pd.get_dummies(df.Countries, prefix='Country')
y

   Country_France  Country_Germany  Country_Spain
0               0                0              1
1               1                0              0
2               0                0              1
3               0                1              0
4               1                0              0

In [6]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

In [7]:
enc_df = pd.DataFrame(enc.fit_transform(df[['Countries']]).toarray())
enc_df

     0    1    2
0  0.0  0.0  1.0
1  1.0  0.0  0.0
2  0.0  0.0  1.0
3  0.0  1.0  0.0
4  1.0  0.0  0.0

In [9]:
y2 = df.join(enc_df)
y2

   Ids Countries    0    1    2
0   11     Spain  0.0  0.0  1.0
1   22    France  1.0  0.0  0.0
2   33     Spain  0.0  0.0  1.0
3   44   Germany  0.0  1.0  0.0
4   55    France  1.0  0.0  0.0

In [20]:
s = pd.Series([1, 2, 3, 4])

In [43]:
x = s.quantile([.1, .25, .5, .75])
x

0.10    1.30
0.25    1.75
0.50    2.50
0.75    3.25
dtype: float64

In [50]:
y2[0].astype(int)

0    0
1    1
2    0
3    0
4    1
Name: 0, dtype: int64

In [37]:
y = x.tolist()
y

[1.3, 1.75, 2.5, 3.25]

In [38]:
y.pop(0)

1.3