# Pandas, getting started

In [1]:
import numpy as np
import pandas as pd

## Things to lookup
* slicing, selecting, and extracting the data
* plotting w/ Matplotlib
* stats over rows
* split-apply-combine:  sliding window of the data, or grouped by categories
* Structure changes
    * melt()
    * pivot()
* join/merge pandas
* SQL equivalents = Group by Join

Cheat Sheet:
https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

## Example

titanic.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890 Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 ...
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Dependencies

tabulate    MD formatting   https://github.com/astanin/python-tabulate
matplotlib  plotting
SciPy       stats
html5lib    read html
BeautifulSoup4

SQLAlchemy  sqlite
pymysql     mysql
psycopg2    postgresSQL

s3fs    AWS S3 access !!!!

titanic["Age"] > 35
0 False
1 True
2 False
...
Name: Age, Length: 891, dtype: bool

class_23 = titanic[titanic["Pclass"].isin([2, 3])]
class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]
age_no_na = titanic[titanic["Age"].notna()]

## Select specific rows
adult_names = titanic.loc[titanic["Age"] > 35, "Name"]
titanic.iloc[9:25, 2:5] ##  rows 10 till 25 and columns 3 to 5.

## assign values
titanic.iloc[0:3, 3] = "anonymous"

# Plots

## Quick Plot
df.plot()
df["station_paris"].plot()
df.plot.scatter(x="station_london", y="station_paris", alpha=0.5)
other plots: ['area', 'bar', 'barh', 'box', 'density', 'hexbin', 'hist', 'kde', 'line', 'pie', 'scatter']
df.iloc[5].plot(kind="bar")
df.plot.bar(stacked=True);
df.plot.hist(stacked=True, bins=20);

df.plot.pie(subplots=True, figsize=(8, 4));
series.plot.pie(figsize=(6, 6));

plt.figure();
df["a"].plot.hist(orientation="horizontal", cumulative=True);

## COlumn manupulation

### Add column
air_quality["london_mg_per_cubic"] = air_quality["station_london"] * 1.882

titanic[["Age", "Fare"]].describe()

titanic.groupby("Sex")["Age"].mean()
titanic.groupby(["Sex", "Pclass"])["Fare"].mean()

titanic["Pclass"].value_counts()  -- count of values
titanic.groupby("Pclass")["Pclass"].count() -- same as value count

titanic.sort_values(by="Age")
titanic.sort_values(by=['Pclass', 'Age'], ascending=False)


titanic.pivot(columns="location", values="value")
pd.pivot_table(values="value", index="location", columns="parameter", aggfunc="mean")


groupby()
unstack()

pandas.melt()

# Combining tables

new_pd = pd.concat([air_quality_pm25, air_quality_no2], axis=0)

In [7]:
df = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                   'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})
df

  key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [8]:
df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})
df2

  key   B
0  K0  B0
1  K1  B1
2  K2  B2

In [9]:
df.join(df2, lsuffix='_caller', rsuffix='_other')

  key_caller   A key_other    B
0         K0  A0        K0   B0
1         K1  A1        K1   B1
2         K2  A2        K2   B2
3         K3  A3       NaN  NaN
4         K4  A4       NaN  NaN
5         K5  A5       NaN  NaN

In [11]:
df.set_index('key').join(df2.set_index('key'))

      A    B
key
K0   A0   B0
K1   A1   B1
K2   A2   B2
K3   A3  NaN
K4   A4  NaN
K5   A5  NaN

In [13]:
df.join(df2.set_index('key'), on='key')

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2   B2
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

In [20]:
df2.axes

[RangeIndex(start=0, stop=3, step=1), Index(['key', 'B'], dtype='object')]

In [21]:
df3 = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
     index=['cobra', 'viper', 'sidewinder'],
     columns=['max_speed', 'shield'])
df3

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [31]:
df3.loc['viper'] == df3.iloc[1]

max_speed    True
shield       True
Name: viper, dtype: bool

In [34]:
df3.hist

<bound method hist_frame of             max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8>

In [35]:
df4 = pd.DataFrame({'A': [0, 0], 'B': [4, 4]})
df5 = pd.DataFrame({'A': [1, 1], 'B': [3, 3]})
take_smaller = lambda s1, s2: s1 if s1.sum() < s2.sum() else s2
df4.combine(df5, take_smaller)

   A  B
0  0  3
1  0  3

In [81]:
df3 = pd.DataFrame([[1, 2], [4, 5], [7, 8], [9,10]],
     index=['cobra', 'viper', 'sidewinder', 'df3-car'],
     columns=['max_speed', 'shield'])
df3

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
df3-car             9      10

In [132]:
df31 = pd.DataFrame([[1, 2], [4, 5], [7, 8], [11, 12]],
     index=['cobra', 'viper', 'sidewinder', 'df31-car'],
     columns=['weight', 'height'])
df31

            weight  height
cobra            1       2
viper            4       5
sidewinder       7       8
df31-car        11      12

In [49]:
pd.concat([df3, df31], axis=1, join='inner')

            max_speed  shield  weight  height
cobra               1       2       1       2
viper               4       5       4       5
sidewinder          7       8       7       8

In [55]:
pd.concat([df3, df31], axis=1, join='outer')

            max_speed  shield  weight  height
cobra             1.0     2.0     1.0     2.0
viper             4.0     5.0     4.0     5.0
sidewinder        7.0     8.0     7.0     8.0
df3-car           9.0    10.0     NaN     NaN
df31-car          NaN     NaN    11.0    12.0

In [80]:
df3.index

Index(['cobra', 'viper', 'sidewinder', 'df3-car'], dtype='object', name='max_speed')

In [53]:
df31.index('')

Index(['cobra', 'viper', 'sidewinder', 'df31-car'], dtype='object')

In [64]:
df3

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
df3-car             9      10

In [71]:
dir(df3.index)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__init__',
 '__init_subclass__',
 '__inv__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_arith_method',
 '_assert_can_do_setop',
 '_attributes',
 '_cache',
 '_can_hold_identifiers_and_holds_name',
 '_can_hold_na',
 '_can_hold_strings',
 '_check_indexing_error',
 '_check_indexing_method',
 '_cleanup',
 '_cmp_method',
 '_comparables',
 '_concat',
 '_constructor',
 '_convert_can_do_setop',
 '_convert_slice_indexer',
 '_convert_tolerance',
 '_data',
 '_deprecated_arg',
 '_difference',
 '_dir_additions',
 '_dir_additions_for_owner',
 '_dir_deletions',
 '_drop_level_numbers',
 '_dtype_to_subclass',
 '_duplicated',
 '_engine',
 '_engine_type',
 '_ensure_array',
 '_filter_indexer_tolerance',
 '_find_common_type_compat',
 '_format_attrs',
 '_format_data',
 '_format_duplicate_message',
 '_format_native_types',
 '_format_space',
 '_format_with_header',
 '_formatter_func',
 '_from_join_target',
 '_get_attributes_dict',
 '_get_engine_target',
 '_get_fill_indexer',
 '_get_fill_indexer_searchsorted',
 '_get_grouper_for_level',
 '_get_indexer',
 '_get_indexer_non_comparable',
 '_get_join_target',
 '_get_level_number',
 '_get_level_values',
 '_get_names',
 '_get_nearest_indexer',
 '_get_partial_string_timestamp_match_key',
 '_get_reconciled_name_object',
 '_get_string_slice',
 '_get_unique_index',
 '_get_values_for_loc',
 '_getitem_slice',
 '_has_complex_internals',
 '_hidden_attrs',
 '_id',
 '_index_as_unique',
 '_index_data',
 '_inner_indexer',
 '_intersection',
 '_intersection_via_get_indexer',
 '_invalid_indexer',
 '_is_all_dates',
 '_is_comparable_dtype',
 '_is_memory_usage_qualified',
 '_is_multi',
 '_is_numeric_dtype',
 '_is_strictly_monotonic_decreasing',
 '_is_strictly_monotonic_increasing',
 '_isnan',
 '_join_level',
 '_join_monotonic',
 '_join_multi',
 '_join_non_unique',
 '_join_precedence',
 '_left_indexer',
 '_left_indexer_unique',
 '_logical_method',
 '_map_values',
 '_maybe_cast_indexer',
 '_maybe_cast_listlike_indexer',
 '_maybe_cast_slice_bound',
 '_maybe_check_unique',
 '_maybe_disable_logical_methods',
 '_maybe_disallow_fill',
 '_maybe_promote',
 '_memory_usage',
 '_mpl_repr',
 '_na_value',
 '_name',
 '_no_setting_name',
 '_outer_indexer',
 '_reduce',
 '_reindex_non_unique',
 '_rename',
 '_require_scalar',
 '_requires_unique_msg',
 '_reset_cache',
 '_reset_identity',
 '_scalar_data_error',
 '_searchsorted_monotonic',
 '_set_names',
 '_shallow_copy',
 '_should_compare',
 '_should_fallback_to_positional',
 '_simple_new',
 '_sort_levels_monotonic',
 '_string_data_error',
 '_summary',
 '_supports_partial_string_indexing',
 '_transform_index',
 '_typ',
 '_unary_method',
 '_union',
 '_validate_can_reindex',
 '_validate_fill_value',
 '_validate_index_level',
 '_validate_indexer',
 '_validate_names',
 '_validate_positional_slice',
 '_validate_sort_keyword',
 '_values',
 '_view',
 '_wrap_intersection_result',
 '_wrap_joined_index',
 '_wrap_setop_result',
 'all',
 'any',
 'append',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asi8',
 'asof',
 'asof_locs',
 'astype',
 'copy',
 'delete',
 'difference',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'duplicated',
 'empty',
 'equals',
 'factorize',
 'fillna',
 'format',
 'get_indexer',
 'get_indexer_for',
 'get_indexer_non_unique',
 'get_level_values',
 'get_loc',
 'get_slice_bound',
 'get_value',
 'groupby',
 'has_duplicates',
 'hasnans',
 'holds_integer',
 'identical',
 'inferred_type',
 'insert',
 'intersection',
 'is_',
 'is_all_dates',
 'is_boolean',
 'is_categorical',
 'is_floating',
 'is_integer',
 'is_interval',
 'is_mixed',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_numeric',
 'is_object',
 'is_type_compatible',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'join',
 'map',
 'max',
 'memory_usage',
 'min',
 'name',
 'names',
 'nbytes',
 'ndim',
 'nlevels',
 'notna',
 'notnull',
 'nunique',
 'putmask',
 'ravel',
 'reindex',
 'rename',
 'repeat',
 'searchsorted',
 'set_names',
 'shape',
 'shift',
 'size',
 'slice_indexer',
 'slice_locs',
 'sort',
 'sort_values',
 'sortlevel',
 'str',
 'symmetric_difference',
 'take',
 'to_flat_index',
 'to_frame',
 'to_list',
 'to_native_types',
 'to_numpy',
 'to_series',
 'transpose',
 'union',
 'unique',
 'value_counts',
 'values',
 'view',
 'where']

In [77]:
df3.index.names

FrozenList([None])

In [94]:
df8 = pd.DataFrame(np.arange(100).reshape(10,10))
df8

    0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [97]:
df8.set_index([9])

     0   1   2   3   4   5   6   7   8
9
9    0   1   2   3   4   5   6   7   8
19  10  11  12  13  14  15  16  17  18
29  20  21  22  23  24  25  26  27  28
39  30  31  32  33  34  35  36  37  38
49  40  41  42  43  44  45  46  47  48
59  50  51  52  53  54  55  56  57  58
69  60  61  62  63  64  65  66  67  68
79  70  71  72  73  74  75  76  77  78
89  80  81  82  83  84  85  86  87  88
99  90  91  92  93  94  95  96  97  98

In [133]:
df32 = ""
df32= df31.copy(deep=True)
df32['old_index'] = df32.index
df32.set_index(['weight'])
df32.reset_index(drop=True, inplace=True)
df32.reindex()
df32

   weight  height   old_index
0       1       2       cobra
1       4       5       viper
2       7       8  sidewinder
3      11      12    df31-car

In [134]:
df31

            weight  height
cobra            1       2
viper            4       5
sidewinder       7       8
df31-car        11      12

In [136]:
from sklearn.metrics import classification_report, confusion_matrix

y_true = ["cat", "ant", "cat", "cat", "ant", "bird"]
y_pred = ["ant", "ant", "cat", "cat", "ant", "cat"]
cm = confusion_matrix(y_true, y_pred, labels=["ant", "bird", "cat"])
cm

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]])

In [141]:
cmtx = pd.DataFrame( cm, index=["ant", "bird", "cat"],  columns=["ant", "bird", "cat"] )
print(cmtx)

      ant  bird  cat
ant     2     0    0
bird    0     0    1
cat     1     0    2

In [143]:
df32 = df31.append(df31)
df32

            weight  height
cobra            1       2
viper            4       5
sidewinder       7       8
df31-car        11      12
cobra            1       2
viper            4       5
sidewinder       7       8
df31-car        11      12

In [144]:
df32.groupby('weight').sum()

        height
weight
1            4
4           10
7           16
11          24

In [145]:
df4 = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
df4

     A      B         C         D
0  foo    one  0.693260 -1.118509
1  bar    one  0.297455 -1.021585
2  foo    two  1.091719  0.830859
3  bar  three -0.105080 -0.293204
4  foo    two  0.350046 -0.845586
5  bar    two  0.954382  1.377916
6  foo    one -0.458791  0.674700
7  foo  three -2.094503  0.265189

In [147]:
df4.groupby('B').sum()

              C         D
B
one    0.531924 -1.465393
three -2.199582 -0.028015
two    2.396146  1.363189

In [154]:
df4['B2'] = df4['B'].str.slice(0, 2)
df4.groupby('B2').sum()

           C         D
B2
on  0.531924 -1.465393
th -2.199582 -0.028015
tw  2.396146  1.363189

In [156]:
df4.groupby('B2').sum()

           C         D
B2
on  0.531924 -1.465393
th -2.199582 -0.028015
tw  2.396146  1.363189